service: ice-trae-bot-poller-test

provider:
  name: aws
  runtime: nodejs8.10
  stage: dev
  region: us-east-1

functions:
  poller:
    handler: index.handler
    events:
      - schedule: rate(1 minute)

package:
  exclude:
    - .env